### ISSUE TITLE
Docker Desktop not starting again! 

### ISSUE THREAD

**Issue by BlackListSec** [fireeye/commando-vm#161]
**Describe the bug and expected behavior**

**To Reproduce**
**Steps to reproduce the behavior:**
Followed Standard install process and all Docker dependencies are failing and landing into the \lib-bad folder. 
![image](https://user-images.githubusercontent.com/62220504/90339835-cb41f100-dfc1-11ea-84f6-11b9e4284662.png)

The obvious was to verify the Processor setting are set  Virtualize Intel VT-x/EPT or AMD-V/RVI. 

![image](https://user-images.githubusercontent.com/62220504/90339662-27a41100-dfc0-11ea-908a-aa8e03181eb5.png)

I've reloaded the docker desktop manually without success to repair. It appears to be related to WSL2 vs. WSL1 provisioning. Nothing thus far seems to fix it. Also looked at a few Docker blogs and no luck. 

**Screenshots**
![image](https://user-images.githubusercontent.com/62220504/90339577-b3696d80-dfbf-11ea-905d-bf0343116bc8.png)

**Version**
 Host Name:                 DESKTOP-EUR5OKI
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                **10.0.19041 N/A Build 19041**
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

**Additional context**
**Docker logs:** 
Version: 2.3.0.4 (46911)
Channel: stable
Sha1: d4f5fcf98140180eeef00e02c1c8bb0ad69e35d3
Started on: 2020/08/16 12:46:25.647
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\Commando\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[12:46:25.788][GUI               ][Info   ] Starting...
[12:46:25.819][ComponentVersions ][Info   ] Edition community
[12:46:25.834][ComponentVersions ][Info   ] Edition community
[12:46:26.085][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[12:46:26.116][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[12:46:26.116][SegmentApi        ][Info   ] Usage statistic: Identify
[12:46:26.241][SegmentApi        ][Info   ] Usage statistic: appLaunched
[12:46:26.874][ApplicationTemplatesTracking][Info   ] Cannot list templates
[12:46:26.874][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[12:46:26.874][SegmentApi        ][Info   ] Usage statistic: heartbeat
[12:46:26.968][LoggingMessageHandler][Info   ] [cc50a90a] <BackendAPIClient start> GET http://backend/version
[12:46:27.030][LoggingMessageHandler][Info   ] [cc50a90a] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 67ms)
[12:46:27.129][LoggingMessageHandler][Info   ] [4eada9d7] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[12:46:27.145][LoggingMessageHandler][Info   ] [4eada9d7] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 19ms)
[12:46:27.161][LoggingMessageHandler][Info   ] [93b39900] <BackendAPIClient start> POST http://backend/migrate/app
[12:46:27.161][LoggingMessageHandler][Info   ] [93b39900] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 4ms)
[12:46:27.161][Engines           ][Debug  ] Starting
[12:46:27.192][LoggingMessageHandler][Info   ] [ef524df2] <BackendAPIClient start> POST http://backend/versionpack/enable
[12:46:27.270][LoggingMessageHandler][Info   ] [ef524df2] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 76ms)
[12:46:27.364][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[12:46:27.364][GoBackendProcess  ][Info   ] Started
[12:46:27.364][MutagenProcess    ][Info   ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[12:46:27.364][MutagenProcess    ][Info   ] Started
[12:46:27.379][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[12:46:27.379][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[12:46:27.379][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[12:46:27.395][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1597596387}
[12:46:27.395][SystrayNotifications][Info   ] Docker is starting
[12:46:28.886][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[12:46:28.886][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[12:46:28.886][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[12:46:28.886][MutagenProcess    ][Info   ] [sync] Session manager initialized
[12:46:29.870][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[12:46:29.886][LoggingMessageHandler][Info   ] [de21f134] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[12:46:31.219][LoggingMessageHandler][Info   ] [de21f134] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 1335ms)
[12:46:31.599][LoggingMessageHandler][Info   ] [913590a4] <Server start> GET http://unix/versions
[12:46:31.716][LoggingMessageHandler][Info   ] [913590a4] <Server end> GET http://unix/versions -> 200 OK (took 103ms)
[12:46:31.785][WSL2Provisioning  ][Info   ] Checking docker-desktop
[12:46:31.807][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[12:46:31.808][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[12:46:31.811][GoBackendProcess  ][Info   ] enabling filesystem caching
[12:46:31.811][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[12:46:31.812][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[12:46:31.814][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[12:46:31.814][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[12:46:31.814][GoBackendProcess  ][Info   ] using mfsymlinks
[12:46:31.821][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[12:46:31.823][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[12:46:31.824][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[12:46:32.157][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\Commando\AppData\Local\Docker\wsl\distro
[12:46:33.829][WSL2Provisioning  ][Error  ] **Failed to set version to docker-desktop: exit code: -1**
 stdout: The attempted operation is not supported for the type of object referenced.

 stderr: 
[12:46:33.844][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[12:46:33.891][LinuxWSL2Engine   ][Info   ] Stopping engine
[12:46:34.000][LinuxWSL2Engine   ][Warning] Failed to send stop message to distro, will terminate abrubtly: 
[12:46:34.128][LoggingMessageHandler][Info   ] [1e947b56] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[12:46:35.102][LoggingMessageHandler][Info   ] [1e947b56] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 969ms)
[12:46:35.698][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[12:46:35.698][LoggingMessageHandler][Info   ] [2662f7d6] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[12:46:35.776][WSL2Provisioning  ][Info   ] Checking docker-desktop
[12:46:35.776][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\Commando\AppData\Local\Docker\wsl\distro
[12:46:35.792][LoggingMessageHandler][Info   ] [2662f7d6] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 95ms)
[12:46:37.256][WSL2Provisioning  ][Error  ] Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

 stderr: 
[12:46:37.256][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[12:46:37.315][LinuxWSL2Engine   ][Info   ] Stopping engine
[12:46:37.440][LinuxWSL2Engine   ][Warning] Failed to send stop message to distro, will terminate abrubtly: 
[12:46:37.518][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[12:46:37.518][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[12:46:37.518][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[12:46:37.518][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1597596397}
[12:46:37.534][SystrayNotifications][Error  ] Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

 stderr: 
[12:46:37.557][GUI               ][Info   ] Sending Bugsnag report d930cb9e-6bab-413e-8ded-b9beb23f0eae...
[12:46:37.650][GUI               ][Info   ] Bugsnag report d930cb9e-6bab-413e-8ded-b9beb23f0eae sent
[12:46:37.650][SegmentApi        ][Info   ] Usage statistic: eventCrash
[12:46:37.666][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[12:46:37.845][Engines           ][Error  ] Start failed with Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 109)
[12:46:37.903][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[12:46:37.909][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[12:46:37.910][GoBackendProcess  ][Info   ] mutagen sync list --output json
[12:46:37.959][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[12:46:37.959][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\

**Comment by day1player** [comment]
Hello there, Please check out issue #94 ..  Nested Virtualization with Docker on a Windows HOST machine is unfortunately not supported by Docker. Based on your VM Settings screenshot, it looks like you are using VMware Workstation (Windows). 

There are some hacks you might be able to do to get it to work, though I will not be able to help with that. This was a big reason our 2020.2 release removed Docker from the standard install 😢.

If you do find a solution feel free to post here.
