### ISSUE TITLE
Unable to start msfconsole - Ruby error

### ISSUE THREAD

**Issue by NoobieLearner** [fireeye/commando-vm#7]
Commando/Boxstarter is installed and other apps and tools seem to be OK - still testing.

When I attempt to run Metasploit - msfconsole - I see the following error.  
Do I need to modify any Ruby environmental variables or update Ruby?   
Traceback (most recent call last):
        6: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
        5: from <internal:gem_prelude>:2:in `require'
        4: from C:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubyge
ms.rb:116:in `<top (required)>'
        3: from C:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubyge
ms.rb:1365:in `<module:Gem>'
        2: from C:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubyge
ms.rb:1365:in `require'
        1: from C:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubyge
ms/specification.rb:18:in `<top (required)>'
C:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubygems/specification
.rb:18:in `require': incompatible library version - C:/metasploit-framework/embe
dded/lib/ruby/2.5.0/x64-mingw32/stringio.so (LoadError)

**Comment by htnhan** [comment]
@NoobieLearner  It is likely related to https://github.com/rapid7/metasploit-framework/issues/11324. Unfortunately, we may not be able to fix this until Ruby has an update.
